# Generated by Django 4.2.7 on 2025-03-29 09:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155, verbose_name="Имя книги")),
                ("author", models.CharField(max_length=155, verbose_name="Автор")),
                ("description", ckeditor.fields.RichTextField(verbose_name="Описание")),
                ("date", models.DateField(verbose_name="Дата выхода")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Роман", "Роман"),
                            ("Фантазия", "Фантазия"),
                            ("Романтика", "Романтика"),
                        ],
                        help_text="Тут должен быть жанр книги!",
                        max_length=155,
                        verbose_name="Тип книги",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
    ]
