# Generated by Django 4.2.7 on 2025-03-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активен"),
        ),
    ]
